### ISSUE TITLE
ERROR ITMS-90535: "Unexpected CFBundleExecutable Key."

### ISSUE THREAD

**Issue by WestFR** [dji-sdk/DJIFlySafeDatabaseResource#1]
Hello DJI Teams !

I want to integrate DJIFlySafeDatabaseResource in my XCode project with podfile.

When I build my app in debug mode, everything are ok ! 👌 
But, when I build my app in release mode, I obtain the error below.

ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/DronieCompanion.app/DJIFlySafeDatabaseResource.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

Do you have any solution for this ?
Thanks all !

**Comment by WestFR** [comment]
I need feedback please....

**Comment by daugauvuontre** [comment]
@WestFR 
I also met this issue, here is how I resolved it:
After `pod install`: 
1. Open xcode, go to DJIFlySafeDatabaseResource > Resources > DJIFlySafeDatabaseResource.bundle > Contents > Info.plist
2. Remove CFBundleExecutable Key in Info.plist

Now you can archive for release.
Problem is we must do these steps after each time do `pod install` again :D

**Comment by WestFR** [comment]
@koodaa-team Thanks to your response !

So, i have fixed this issue with your instructions.
And for response to your problem below : "Problem is we must do these steps after each time do pod install again :D".

I have forked this repository and push one commit with your informations (removed of CFBundleExecytable key). And i have proposed one pull request for closed this issue for all time.

In waiting for pull request response, i propose you to update your podfile with below : 
`pod 'DJIFlySafeDatabaseResource', :git => 'https://github.com/WestFR/DJIFlySafeDatabaseResource.git '`

Thus, you download the repository corresponding to the pull request awaiting its validation!

I close this issue in waiting for pull request response.
Thanks again !

**Comment by josechagas** [comment]
Is there any news about this error?

**Comment by WestFR** [comment]
@josechagas 

Refer to commit f58f6a0 (see screenshoot below).
Now it's work. You can use directly this repository thanks to the DJI merge.

<img width="900" alt="Capture d’écran 2020-07-24 à 11 45 55" src="https://user-images.githubusercontent.com/21226632/88379488-5c4af100-cda3-11ea-9075-45844594ca1b.png">
